baseURL = "https://blog.strayphotography.com"
languageCode = "en-us"
title = "Stray Photography Blog"
theme = "hugo-theme-novela"
summaryLength = 34
copyright = "Stray Photography"

[params]
  google_fonts = [
    ["Roboto Slab", "400, 700"],
    ["Raleway", "400, 400i, 700, 700i"]
  ]
  heading_font = "Roboto Slab"
  body_font = "Raleway"

pygmentsstyle = "monokai"
paginate = 6.0

[social]
twitter = "matt_strayer"
instagram = "matt_strayer"


[taxonomies]
author = "authors"