baseURL = "http://blog.strayphotography.com/"
languageCode = "en-us"
title = "Stray Photography Blog"
theme = "hugo-theme-attila"
publishDir = "docs"
[params]
  cover = "images/bg.jpg" # Large cover image.
  logo = "/images/logo.png" # Small logo shown opposite the menu toggle.
  navigation = true # Display the menu toggle.
  twitter = "matt_strayer" # Add a menu link to this Twitter handle.
  instagram = "matt_strayer" # Add a menu link to this Instagram page.